---
name: PR Check

on:
  pull_request:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: false

env:
  NODE_VERSION: 20.x

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install
      - run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - run: echo 'No FVTT tests yet...'
